const ShopActionTypes = {
    FETCH_COLLECTIONS_START: 'FETCH_COLLECTIONS_START',
    FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
    FETCH_COLLECTIONS_FAILURE: 'FETCH_COLLECTIONS_FAILURE',
    FETCH_SINGLE_PRODUCT_START: "FETCH_SINGLE_PRODUCT_START",
    FETCH_SINGLE_PRODUCT_SUCCESS: "FETCH_SINGLE_PRODUCT_SUCCESS",
    FETCH_SINGLE_PRODUCT_FAILURE: "FETCH_SINGLE_PRODUCT_FAILURE"
}

export default ShopActionTypes;